import Header from '@/components/layout/Header'
import MatchListClient from './MatchListClient'
import type { MatchRequest } from '@/types'

export const metadata = {
  title: '섭외문의 · 정보',
  description: '섭외문의를 등록하시면 강사님 프로필/강의제안서를 무료로 받아보실 수 있습니다.',
}

// TODO: Supabase 연동 후 아래 mock 데이터 교체
const MOCK_REQUESTS: MatchRequest[] = [
  {
    id: '1',
    category: '헤어',
    title: '헤어 전문 강사 섭외 문의 (입문반 운영)',
    location_si: '서울',
    location_gu: '은평구',
    preferred_date: '2026-04-07',
    lecture_type: '출강강의',
    description: '헤어 입문 과정 클래스 강사를 찾고 있습니다. 주 2회, 약 2개월 과정입니다.',
    is_published: true,
    contact_name: '',
    contact_phone: '',
    status: 'pending',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    category: '메이크업',
    title: '[VIP] 백화점 키즈 브랜드 주관 부모대상 메이크업 강의',
    location_si: '광주',
    location_gu: '서구',
    preferred_date: '2026-03-25',
    lecture_type: '출강강의',
    description: '백화점 문화센터에서 진행할 부모 대상 메이크업 원데이 클래스 강사를 구합니다.',
    is_published: true,
    contact_name: '',
    contact_phone: '',
    status: 'pending',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    category: '메이크업',
    title: '[VIP] 백화점 키즈 브랜드 주관 부모대상 메이크업 강의 (2차)',
    location_si: '광주',
    location_gu: '서구',
    preferred_date: '2026-03-25',
    lecture_type: '출강강의',
    description: '1차 강의 성황리에 마무리 후 2차 진행 강사를 구합니다.',
    is_published: true,
    contact_name: '',
    contact_phone: '',
    status: 'pending',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    category: '피부관리',
    title: '피부관리 전문 강사 섭외 (기업 교육)',
    location_si: '서울',
    location_gu: '마포구',
    preferred_date: '2026-04-07',
    lecture_type: '출강강의',
    description: '기업 임직원 대상 피부관리 교육 강사를 찾습니다.',
    is_published: true,
    contact_name: '',
    contact_phone: '',
    status: 'pending',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    category: '퍼스널컬러',
    title: '퍼스널컬러 진단 클래스 강사 모집',
    location_si: '서울',
    location_gu: '강남구',
    preferred_date: '2026-03-30',
    lecture_type: '클래스운영',
    description: '문화센터에서 진행할 퍼스널컬러 진단 원데이 클래스 강사를 구합니다.',
    is_published: true,
    contact_name: '',
    contact_phone: '',
    status: 'pending',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    category: '네일',
    title: '네일아트 입문 온라인 강의 강사 섭외',
    location_si: '경기',
    location_gu: '안양시',
    preferred_date: '2026-03-20',
    lecture_type: '온라인강의',
    description: '비대면 네일아트 입문 강의 진행 가능한 강사를 찾습니다.',
    is_published: true,
    contact_name: '',
    contact_phone: '',
    status: 'pending',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    category: '웨딩/업스타일',
    title: '미용학원 웨딩/업스타일 과정 담당 강사',
    location_si: '서울',
    location_gu: '은평구',
    preferred_date: '2026-09-30',
    lecture_type: '클래스운영',
    description: '미용학원 신규 개설 과정 담당 강사를 장기 채용합니다.',
    is_published: true,
    contact_name: '',
    contact_phone: '',
    status: 'pending',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    category: 'SMP',
    title: 'SMP 교육 전문 강사 섭외',
    location_si: '서울',
    location_gu: '은평구',
    preferred_date: '2026-05-05',
    lecture_type: '출강강의',
    description: 'SMP(두피문신) 관련 교육 가능한 전문 강사를 구합니다.',
    is_published: true,
    contact_name: '',
    contact_phone: '',
    status: 'pending',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
]

export default function MatchPage() {
  return (
    <>
      <Header variant="light" />
      <MatchListClient items={MOCK_REQUESTS} />
    </>
  )
}
